name: Determine Next Version
inputs:
  currentBranch:
    description: 'Branch name'
    required: true
  versionFilePath:
    description: 'Path to the version.txt'
    required: true
  shouldIncrementMajor:
    description: 'Increment the major version'
    required: true
    default: 'false'
  shouldIncrementMinor:
    description: 'Increment the minor version'
    required: true
    default: 'false'
outputs:
  newVersionNumber:
    description: 'The new version'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine next version
      id: version
      shell: pwsh
      run: |
        function Get-InsightVersion {
            # Get the directory of the current script
            $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
            # Go up one level from the script's directory
            $parentDir = Split-Path -Parent $scriptDir
            $versionFilePath = Join-Path -Path $parentDir -ChildPath "version.txt"
            
            if (-not (Test-Path -Path $versionFilePath)) {
                Write-Error "Version file not found at $versionFilePath"
                return $null
            }

            $version = Get-Content -Path $versionFilePath -Raw
            return $version.Trim()
        }
        
        $newVersion = Get-InsightVersion
        echo "Determined version: $newVersion"

        # Export output
        echo "::set-output name=newVersionNumber::$newVersion"
