name: Determine Next Version
inputs:
  currentBranch:
    description: 'Branch name'
    required: true
  versionFilePath:
    description: 'Path to the version.txt'
    required: true
  shouldIncrementMajor:
    description: 'Increment the major version'
    required: true
    default: 'false'
  shouldIncrementMinor:
    description: 'Increment the minor version'
    required: true
    default: 'false'
outputs:
  newVersionNumber:
    description: 'The new version'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine next version
      id: version
      shell: pwsh
      run: |
        function Get-InsightVersion {
            # Use the GITHUB_WORKSPACE environment variable to get the repository root directory
            $repoRootDir = $env:GITHUB_WORKSPACE

            # Point directly to the version.txt in the root of the repo
            $versionFilePath = Join-Path -Path $repoRootDir -ChildPath "version.txt"
            
            if (-not (Test-Path -Path $versionFilePath)) {
                Write-Error "Version file not found at $versionFilePath"
                return $null
            }

            # Read the version from the file
            $version = Get-Content -Path $versionFilePath -Raw
            $version = $version.Trim()

            # Print the version explicitly to the console
            Write-Output "Determined version: $version"

            return $version
        }

        # Call the function and output the result
        $newVersion = Get-InsightVersion
        echo "Determined version: $newVersion"

        # Debug output: Check value before exporting
        echo "Debug: New version is: $newVersion"

        # Export output
        echo "newVersionNumber=$newVersion" >> $GITHUB_OUTPUT
