name: Determine Next Version
inputs:
  currentBranch:
    description: 'Branch name'
    required: true
  versionFilePath:
    description: 'Path to the version.txt'
    required: true
  shouldIncrementMajor:
    description: 'Increment the major version'
    required: true
    default: 'false'
  shouldIncrementMinor:
    description: 'Increment the minor version'
    required: true
    default: 'false'
outputs:
  newVersionNumber:
    description: 'The new version'
    value: ${{ steps.version.outputs.newVersionNumber }}
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine next version
      id: version
      shell: pwsh
      run: |
        function Get-NextVersion {
            param(
                [string]$currentVersion,
                [string]$branch,
                [bool]$incrementMajor,
                [bool]$incrementMinor
            )
            
            $versionParts = $currentVersion.Split('.')
            $major = [int]$versionParts[0]
            $minor = [int]$versionParts[1]
            $patch = [int]$versionParts[2]
            $revision = if ($versionParts.Count -gt 3) { [int]$versionParts[3] } else { 0 }

            if ($branch -eq "master") {
                if ($incrementMajor) {
                    # Master branch + major increment
                    $major++
                    $minor = 0
                    $patch = 0
                    $revision = 0
                }
                elseif ($incrementMinor) {
                    # Master branch + minor increment
                    $minor++
                    $patch = 0
                    $revision = 0
                }
                else {
                    # Master branch + patch increment
                    $patch++
                    $revision = 0
                }
            }
            elseif ($branch -like "release/*") {
                # Release branch - increment revision only
                $revision++
            }
            else {
                # Other branches - don't modify version
                return $currentVersion
            }

            # Return the appropriate version format
            if ($branch -eq "master") {
                return "$major.$minor.$patch"
            }
            else {
                return "$major.$minor.$patch.$revision"
            }
        }

        # Get current version
        $versionFilePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "version.txt"
        
        if (-not (Test-Path -Path $versionFilePath)) {
            Write-Error "Version file not found at $versionFilePath"
            exit 1
        }

        $currentVersion = (Get-Content -Path $versionFilePath -Raw).Trim()
        Write-Output "Current version: $currentVersion"

        # Convert string inputs to boolean
        $incMajor = "${{ inputs.shouldIncrementMajor }}" -eq 'true'
        $incMinor = "${{ inputs.shouldIncrementMinor }}" -eq 'true'
        $branch = "${{ inputs.currentBranch }}"

        # Calculate next version
        $newVersion = Get-NextVersion -currentVersion $currentVersion -branch $branch -incrementMajor $incMajor -incrementMinor $incMinor
        Write-Output "New version: $newVersion"

        # Update version file
        Set-Content -Path $versionFilePath -Value $newVersion -NoNewline

        # Set output
        echo "newVersionNumber=$newVersion" >> $env:GITHUB_OUTPUT