name: Build Env1

on:
  workflow_call:
    inputs:
      buildconfig:
        required: true
        type: string
      
jobs:
  BuildAndPack:
    environment: 
      name: env1 
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    
    - name: Show Server Variables
      run: echo ${{ inputs.buildconfig }}