name: Test Json parsing

on:
  push

jobs:  
  Variables:  
    runs-on: windows-2019
    outputs:
      buildconfig: ${{ steps.read-json.outputs.buildconfig }}
      
    steps:
    - uses: actions/checkout@v3




    - name: Show file content
      run: |
          Get-Content config.json
        
    - name: Read and Parse JSON
      run: |
          try {
            $json = Get-Content -Raw config.json | ConvertFrom-Json
            Write-Output "Parsed JSON: $($json | ConvertTo-Json -Depth 100)"
          } catch {
            Write-Error "Error parsing JSON: $_"
          }





    - name: Read json
      id: read-json
      shell: pwsh
      run: |
        echo "::set-output name=buildconfig::$(Get-Content -Raw config.json)"
#        echo "::set-output name=buildconfig::$(Get-Content -Raw config.json | ConvertFrom-Json)"

    - name: Show Server Variables
      run: |
        $json = ConvertFrom-Json -InputObject "${{ steps.read-json.outputs.buildconfig }}"
        $nameAttribute = $json.name
        Write-Output "Json Name: $nameAttribute"


  Call-Env1_Build:
    needs: Variables
    uses: ./.github/workflows/Env1_Build.yml
    with:
        buildconfig: ${{ needs.Variables.outputs.buildconfig }}
    secrets: inherit

  Call-Env2_Build:
      needs: Variables
      uses: ./.github/workflows/Env2_Build.yml
      with:
          buildconfig: ${{ needs.Variables.outputs.buildconfig }}
      secrets: inherit