name: Test Json parsing

on:
  push

jobs:  
  Variables:  
    runs-on: windows-2019
    outputs:
      serverVersion: ${{ steps.get_version.outputs.srvVersion }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Run PowerShell script to get server version
      id: get_version
      run: |
        $filePath = 'config.json'
          $serverName = 'tweb'
          $variableName = 'srvVersion'
          pwsh ./.github/workflows/getServerVersion.ps1 -filePath $filePath -serverName $serverName -variableName $variableName
      shell: pwsh
  
    - name: Show Server Variables
      run: |
          echo "The 'srvVersion' server version is ${{ steps.get_version.outputs.srvVersion }}"






  Call-Env1_Build:
    needs: Variables
    if: ${{ needs.Variables.outputs.srvVersion == '6' }}
    uses: ./.github/workflows/Env6_Build.yml
    with:
        serverVersion: ${{ needs.Variables.outputs.serverVersion }}
    secrets: inherit

  Call-Env2_Build:
      needs: Variables
      if:  ${{ needs.Variables.outputs.srvVersion == '75' }}
      uses: ./.github/workflows/Env75_Build.yml
      with:
          serverVersion: ${{ needs.Variables.outputs.serverVersion }}
      secrets: inherit